### ISSUE TITLE
Improve picking performance

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#513] opened 2020-12-23 20:34 UTC
Currently when picking we render to a pick buffer that is the same size as the canvas.

This is unneccessary, because we can render less pixels for picking, ie:

* size the pick buffer to 1x1 pixels
* size the viewport to 1x1 pixels
* set the picking projection matrix to a tight frustum, fitted to the buffer/viewport size

GLGE picking for reference: https://github.com/supereggbert/GLGE/blob/master/src/scene/glge_scene.js#L727

**Comment by Kurtil** [comment] 2023-10-05 15:25
Duplicate of #1076.

**Closed** 2023-11-08 10:42 UTC
Labels: enhancement
