### ISSUE TITLE
Module not found: Error: Can't resolve 'asciify-image'

### ISSUE THREAD

**Issue by hefujie1988** [xeokit/xeokit-sdk#857] opened 2022-05-08 08:57 UTC
Warning: ./node_modules/@xeokit/xeokit-sdk/dist/xeokit-sdk.es.js 103411:11-21
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\lib\dependencies\ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\lib\Compilation.js:1454:24)
    at E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\lib\Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\lib\Compilation.js:1253:28)
    at E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\lib\Compiler.js:672:17
    at _done (eval at create (E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:36:22)
    at E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\lib\Compilation.js:1185:12
93m    at E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\webpack\lib\Compilation.js:1097:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
 @ ./src/app/pages/home-page/home-page.component.ts
 @ ./src/app/pages/home-page/home-page.module.ts
 @ ./src/app/pages/pages.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

Warning: ./node_modules/@xeokit/xeokit-sdk/dist/xeokit-sdk.es.js
Module not found: Error: Can't resolve 'asciify-image' in 'E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\xeokit-sdk\dist'
resolve 'asciify-image' in 'E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\xeokit-sdk\dist'
  Parsed request is a module
  using description file: E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\xeokit-sdk\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in E:/XeokitBIM_Projects/AngStrom_Projects/AngStrom/AngStrom/ClientApp/src
        using description file: E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\package.json (relative path: ./src/asciify-image)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image.js doesn't exist
            as directory
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image doesn't exist
      E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\xeokit-sdk\dist\node_modules doesn't exist or is not a directory
      E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\xeokit-sdk\node_modules doesn't exist or is not a directory
      E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\node_modules doesn't exist or is not a directory
      E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\node_modules doesn't exist or is not a directory
      E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\node_modules doesn't exist or is not a directory
      E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\node_modules doesn't exist or is not a directory
      E:\XeokitBIM_Projects\AngStrom_Projects\node_modules doesn't exist or is not a directory
      E:\XeokitBIM_Projects\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
      looking for modules in E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules
        using description file: E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\package.json (relative path: ./node_modules/asciify-image)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image.tsx doesn't exist
m            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image.js doesn't exist
            as directory
              E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image doesn't exist
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image.ts]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image.tsx]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image.mjs]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\asciify-image.js]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\xeokit-sdk\dist\node_modules]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\xeokit-sdk\node_modules]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\@xeokit\node_modules]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\node_modules]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\node_modules]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\node_modules]
[E:\XeokitBIM_Projects\AngStrom_Projects\node_modules]
[E:\XeokitBIM_Projects\node_modules]
[E:\node_modules]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image.ts]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image.tsx]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image.mjs]
[E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\node_modules\asciify-image.js]
 @ ./node_modules/@xeokit/xeokit-sdk/dist/xeokit-sdk.es.js
 @ ./src/app/pages/home-page/home-page.component.ts
 @ ./src/app/pages/home-page/home-page.module.ts
 @ ./src/app/pages/pages.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

Warning: E:\XeokitBIM_Projects\AngStrom_Projects\AngStrom\AngStrom\ClientApp\src\app\pages\home-page\home-page.component.ts depends on '@xeokit/xeokit-sdk'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by xeolabs** [comment] 2022-05-08 09:17
Sorry, this doesn't give us any information on how to reproduce the error, so need to close it to prevent confusion. If we could have a way to reproduce, then possibly we can reopen. Please note that we don't debug issues that are not within the scope of xeokit, application building/integration glitches, or caused by issues with Angular/React etc.

**Closed by xeolabs** 2022-05-08 09:17 UTC
