### ISSUE TITLE
mouse wheel: Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by NeluQi** [xeokit/xeokit-sdk#763] opened 2021-11-10 17:39 UTC
When scrolling the mouse wheel, this message appears in the console

npm dependencies : "@xeokit/xeokit-sdk": "2.0.14"

import from '@xeokit/xeokit-sdk/dist/xeokit-sdk.min.es.js';

Unable to preventDefault inside passive event listener invocation.
WM._.addEventListener._mouseWheelHandler @ xeokit-sdk.min.es.js:81

![image](https://user-images.githubusercontent.com/16963395/141164089-97f55ad9-a62f-444a-b6c5-a1f2903fbb30.png)

![image](https://user-images.githubusercontent.com/16963395/141164411-102fcec2-4d9d-4fe3-a24e-96a3c1bd88f8.png)

**Comment by xeolabs** [comment] 2021-11-11 14:19
Duplicate of #756. PR on this is most welcome.

**Closed by xeolabs** 2021-11-11 14:19 UTC
