### ISSUE TITLE
warning on asciify-image package

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#977] opened 2022-12-19 16:46 UTC
im using xeokit-sdk version 2.3.3 with react 18 running on node 18, when im starting the project in dev mode i get warning about a module not found (asciify-image) , but when im using the app on the browser its working and no warning is displayed
![image](https://user-images.githubusercontent.com/50522164/208476640-713d4636-0b46-41ab-aba3-cab90082b452.png)
 i wonder if its a webpack issue or something else

**Comment by mlankamp** [comment] 2022-12-28 13:53
See https://github.com/xeokit/xeokit-sdk/issues/912

**Comment by xeolabs** [comment] 2023-05-10 06:35
Closing as a duplicate of #912

**Closed by xeolabs** 2023-05-10 06:35 UTC
