### ISSUE TITLE
Buggy Camera Control pivoting option

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#181] opened 2019-10-17 09:54 UTC
There is two problems here : 
- When pivoting on nothing, the dot is displayed at the origin.
- When pivoting on an entity, the dot is displayed on the last pivot point then moved.

![1f05416c039fa783790b702cc2a4696b](https://user-images.githubusercontent.com/22523482/66998438-8bc22400-f0d4-11e9-9b61-3b5755ed6622.gif)

**Comment by xeolabs** [comment] 2020-12-15 09:11
When pivoting on nothing, pivoting defaults to the origin, and the dot is positioned at the origin to indicate that, which is by design. Do have a different preference for that behaviour?

For the second point, is the issue that the dot is momentarily displayed at its old location before it switches to its new location?

**Comment by xeolabs** [comment] 2020-12-19 10:22
Fixed by #502

**Closed by xeolabs** 2020-12-19 10:22 UTC
