### ISSUE TITLE
camera bug

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#443] opened 2020-10-07 13:45 UTC
Hi there,

Apologies for the less than specific title but I'm not quite sure what's going wrong, so I'd rather just illustrate it with a gif:

![xeokit-2d-3d-camera-bug](https://user-images.githubusercontent.com/38168628/95337977-b9d6e000-08b2-11eb-93e3-59074d1a6b9a.gif)

This is from your public demo on https://xeokit.io/demo.html?projectId=OTCConferenceCenter&tab=storeys

Switching to 2D mode (`ortho` + `planView`, I believe), then switching back to 3D (`orbit` + `perspective`), then clicking on either TOP or BOTTOM on the NavCube causes this behaviour where the model seems to completely disappear.

What we were able to find is that it only happens when TOP or BOTTOM is clicked on the cube; it seems to work fine with the rest.

We've also done some digging and saw that the `eye`, `look` and `up` properties of the camera get set to `[NaN, NaN, NaN]` when this happens.

Could you please look into this?

Thanks

**Comment by xeolabs** [comment] 2020-10-07 14:02
Hi @barnabasmolnar , this is a duplicate of #289. 

It's caused by a limitation in the ````CameraControl```` math for pivoting (click then drag), where pivoting breaks when the camera happens to be looking directly downwards at the time that you begin drag/pivoting.

Essentially ````CameraControl````  needs a small math fix to make it robust for that particular case (see #289 for details). 

I had a quick go at it, but it didn't work perfectly. 

I'll have another go at it, but if any math geek sees an obvious fix, would be most welcome.

Bumping this up a priority.

**Comment by xeolabs** [comment] 2020-12-09 19:57
Fixed by https://github.com/xeokit/xeokit-sdk/issues/289 in release 1.5.1+

**Closed by xeolabs** 2020-12-09 19:57 UTC
