### ISSUE TITLE
Problems using the tool to save the BCF viewpoint

### ISSUE THREAD

**Issue by lanjoni** [xeokit/xeokit-sdk#910] opened 2022-08-04 20:21 UTC
The bug
I'm having problems using the tool to save the BCF viewpoint. Basically, there is no change of viewpoint values when I walk through the model, select objects or make any kind of modification: it simply saves only the initial viewpoint.

To Reproduce

    Go to BCF_SaveViewpoint_MultipleModels example;
    Click on Download BCF Viewpoint after changing the view or performing some action;
    Make another change, and try downloading again;
    Note that there is no data change for viewpoint;

Expected behavior
It was expected that there would be a change to the current viewpoint, so that it is possible to save a viewpoint.

Desktop:

    OS: MacOS
    Browser: Firefox
    Version: 103.0.1 (64-bit)

**Comment by xeolabs** [comment] 2022-08-05 09:14
Duplicate of #909, which is fixed

**Closed by xeolabs** 2022-08-05 09:14 UTC

**Comment by lanjoni** [comment] 2022-08-05 19:28
It's not duplicated. This issue is related to the other example for saving the BCF viewpoint. To test: open the model, browse through it, and download the JSON, so that then continue browsing and download again. The points do not change, as it is not possible to save the user's current viewpoint, only the initial one.

**Comment by lanjoni** [comment] 2022-08-05 19:28
> Duplicate of #909, which is fixed

It's not duplicated. This issue is related to the other example for saving the BCF viewpoint. To test: open the model, browse through it, and download the JSON, so that then continue browsing and download again. The points do not change, as it is not possible to save the user's current viewpoint, only the initial one.
